### ISSUE TITLE
Question: Street View Publish API

### ISSUE THREAD

**Issue by rares-lupascu** [bbsimonbb/xmp-jpeg#1]
Hey

before i dig into this code ... could this help me upload a photo directly to [Street View Publish API](https://developers.google.com/streetview/publish/first-app) ?

thanks

**Comment by bbsimonbb** [comment]
It does what it says it does : client side image compression and XMP. At the time, this seemed a completely untreated subject. I don't know if that's still the case, and I don't know what your requirements are for Street View, sorry.
